#! /bin/bash
./../uploader/nodemcu-uploader.py \
    upload \
        src/config.lua:config.lua \
        src/init.lua:init.lua \
        src/webserver.lua:webserver.lua \
        src/webserver-header.lua:webserver-header.lua \
        src/webserver-request.lua:webserver-request.lua \
        src/MPU6050.lua:MPU6050.lua \
        scripts/status.lua:usr/status.lua \
        scripts/sensor.lua:usr/sensor.lua \
        scripts/htmlstatus.lua:usr/htmlstatus.lua \
        ../flash/flashdaemon.lua:flashdaemon.lua \
#    --verify=sha1